# Site settings
title: JS for all of us
url: http://jsforallof.us
description: "Short, in-depth explanations of JavaScript code and concepts"
# baseurl: "http://jsforallof.us"

# Build settings
markdown: kramdown
permalink: pretty
